server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: 29092002

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

app:
  service-name: Identity Service
  message: Identity configuration loaded from GitHub
